default:
  image: amazoncorretto:11.0.7
  before_script:
    - ': before_script'
    - java --version
    - chmod +x mvnw
    - export MAVEN_OPTS="-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/"

cache:
  key: maven-cache
  paths:
    - $CI_PROJECT_DIR/.m2/

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - ./mvnw test $MAVEN_OPTS

integration_tests:
  stage: test
  script:
    - ./mvnw failsafe:verify $MAVEN_OPTS

build_package:
  stage: build
  script:
    # -U, --update-snapshots
    # Forces a check for updated releases and snapshots on remote repositories
    # Ref: https://books.sonatype.com/mvnref-book/reference/running-sect-options.html
    - ./mvnw clean install -U -DskipTests $MAVEN_OPTS
  artifacts:
    paths:
      - kotlin/kotlin-common/target/*.jar
      - kotlin/kotlin-kafka-consumer/target/*.jar
      - kotlin/kotlin-kafka-producer/target/*.jar
      - kotlin/kotlin-starter/target/*.jar
      - java/java-common/target/*.jar
      - java/java-kafka-consumer/target/*.jar
      - java/java-kafka-producer/target/*.jar
      - java/java-starter/target/*.jar
    expire_in: 1 hour
