spring:
  task.scheduling.pool.size: 2
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id

server:
  port: 8080

app:
  kafka:
    topic-name: spring.kafka.topic
    scheduler-fixed-rate: 10000
  is-consumer-enabled: true
  is-producer-enabled: true
